import React from 'react';
import {
  AlertTriangle,
  ArrowLeft,
  ArrowRight,
  Ban,
  Building,
  Calendar,
  Check,
  ChevronLeft,
  ChevronRight,
  CreditCard,
  Edit,
  Eye as View,
  FileText,
  Filter,
  Home,
  Info,
  Loader2,
  LogOut,
  Mail,
  MapPin,
  Package,
  Phone,
  Plus,
  RefreshCw,
  Search,
  Send,
  Settings,
  Trash,
  User,
  Users,
  X,
  type LucideIcon,
} from 'lucide-react';

export type Icon = LucideIcon;

export const Icons = {
  logo: Building,
  spinner: Loader2,
  search: Search,
  mail: Mail,
  plus: Plus,
  minus: X,
  close: X,
  check: Check,
  users: Users,
  user: User,
  packages: Package,
  view: View,
  edit: Edit,
  trash: Trash,
  home: Home,
  send: Send,
  info: Info,
  warning: AlertTriangle,
  settings: Settings,
  calendar: Calendar,
  ban: Ban,
  building: Building,
  creditCard: CreditCard,
  refresh: RefreshCw,
  filter: Filter,
  arrowLeft: ArrowLeft,
  arrowRight: ArrowRight,
  chevronLeft: ChevronLeft,
  chevronRight: ChevronRight,
  mapPin: MapPin,
  phone: Phone,
  fileText: FileText,
  logout: LogOut,
}; 